### PR TITLE
:liptsick: fix safari timer input visibility

### PR DESCRIPTION
**Pull request by maxired**
d15052af-83f9-400c-b36c-97a6103e576c

this Pr fixes the fact that the timer input is not correct on safari.
this is due to the fact that safari does not vertically center the input content, when specifying an `height` on it

### CODE REVIEW

**Comment by staff0rd** [comment]
This appears to be optimised for the space owner only. The text is not vertically centered for the non-space-owner, see screenshot:
image

**Comment by maxired** [comment]
thanks for checking, will fix

**Comment by maxired** [comment]
> Text is not vertically aligned for the logged out user.

this does not have to be, we want to let space for the optional `paused` button.

> In Firefox (pictured), scroll bar buttons are visible and the right-hand side text is clipped.

good catch ! should be fixed now

**Comment by staff0rd** [comment]
> want to let space for the optional paused button.

weird, but ok

> should be fixed now

confirmed:

image

**Pull request merged**
