### PR TITLE
Adds templates that don't require parameters

### PR DESCRIPTION
**Pull request by AymericG**
image

### CODE REVIEW

**Comment by maxired** [comment]
thanks good job !

I noticed some UI issue with the current values in the template.

- in the 'how are you template', the wall don't match the emojies

Screenshot 2023-03-27 at 15 23 46
Screenshot 2023-03-27 at 15 23 39

- we should take for safety room when placing elements to be close to the dropdown

Screenshot 2023-03-27 at 15 21 39

I don't think we should use text emojis, as they won't render the same depending of OSs


Screenshot 2023-03-27 at 15 21 43

I previously discussed, I don't think we in the long term keep serializing the whole template here, but rather fetching data from a space, so this can be more easily updated.

**Comment by maxired** [comment]
regarding the preview images:
 - probably we should x2 them in term of size, to look ok on retina displays.
 - for the big screen activity I would try to use a less flashy color inside the screen,

**Comment by AymericG** [comment]
1. Yes for using spaces as templates.
2. Also I realized the elements are not locked when inserted.

**Comment by AymericG** [comment]
Regarding your comment about walls. I made them circular, and smaller than the emojis, so that the avatars can overlap with them.

**Comment by AymericG** [comment]
I will do the changes to the templates you suggest once we have them in dedicated spaces

**Pull request merged**
